name: EAS Build
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Install and build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm
      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      - name: Install dependencies
        run: |
          npm install
          npm ci
      - name: Run tests
        run: npm test -- --ci --coverage --maxWorkers=2
      - name: Setup EAS Build
        env:
          EXPO_ANDROID_KEYSTORE_BASE64: ${{ secrets.EXPO_ANDROID_KEYSTORE_BASE64 }}
          EXPO_ANDROID_KEYSTORE_PASSWORD: ${{ secrets.EXPO_ANDROID_KEYSTORE_PASSWORD }}
          EXPO_ANDROID_KEY_PASSWORD: ${{ secrets.EXPO_ANDROID_KEY_PASSWORD }}
          EXPO_ANDROID_KEYSTORE_ALIAS: ${{ secrets.EXPO_ANDROID_KEYSTORE_ALIAS }}
          EXPO_APPLE_TEAM_ID: ${{ secrets.EXPO_APPLE_TEAM_ID }}
          EXPO_APPLE_DISTRIBUTION_CERT_BASE64: ${{ secrets.EXPO_APPLE_DISTRIBUTION_CERT_BASE64 }}
          EXPO_APPLE_DISTRIBUTION_CERT_PASSWORD: ${{ secrets.EXPO_APPLE_DISTRIBUTION_CERT_PASSWORD }}
          EXPO_APPLE_PROVISIONING_PROFILE_BASE64: ${{ secrets.EXPO_APPLE_PROVISIONING_PROFILE_BASE64 }}
        run: |
          mkdir -p eas-builds
          echo $EXPO_ANDROID_KEYSTORE_BASE64 | base64 --decode > eas-builds/android-keystore.jks
          echo $EXPO_APPLE_DISTRIBUTION_CERT_BASE64 | base64 --decode > eas-builds/dist-cert.p12
          echo $EXPO_APPLE_PROVISIONING_PROFILE_BASE64 | base64 --decode > eas-builds/profile.mobileprovision
          echo '{
            "android": {
              "keystore": {
                "keystorePath": "eas-builds/android-keystore.jks",
                "keystorePassword": "'$EXPO_ANDROID_KEYSTORE_PASSWORD'",
                "keyAlias": "'$EXPO_ANDROID_KEYSTORE_ALIAS'",
                "keyPassword": "'$EXPO_ANDROID_KEY_PASSWORD'"
              }
            },
            "ios": {
              "distributionCertificate": {
                "path": "eas-builds/dist-cert.p12",
                "password": "'$EXPO_APPLE_DISTRIBUTION_CERT_PASSWORD'"
              },
              "provisioningProfilePath": "eas-builds/profile.mobileprovision"
            }
          }' > credentials.json
      - name: Build on EAS
        run: eas build --platform all --non-interactive --no-wait
      - name: Submit to app stores
        env:
          EXPO_APPLE_ID: ${{ secrets.EXPO_APPLE_ID }}
          EXPO_ASC_APP_ID: ${{ secrets.EXPO_ASC_APP_ID }}
          EXPO_APPLE_TEAM_ID: ${{ secrets.EXPO_APPLE_TEAM_ID }}
        run: |
          echo '{
            "cli": {
              "version": ">= 3.13.3",
              "appVersionSource": "remote"
            },
            "submit": {
              "production": {
                "ios": {
                  "appleId": "'$EXPO_APPLE_ID'",
                  "ascAppId": "'$EXPO_ASC_APP_ID'",
                  "appleTeamId": "'$EXPO_APPLE_TEAM_ID'"
                }
              }
            }
          }' > eas-submit.json
          eas submit --platform ios --non-interactive --latest --config eas-submit.json
          eas submit --platform android --non-interactive --latest