name: EAS Build
on:
  push:
    branches:
      # - main
      - eas-ci
  workflow_dispatch:

jobs:
  build:
    name: Install and build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm
      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
      - name: Build on EAS
        run: eas build --platform all --non-interactive
      - name: Submit to app stores
        run: eas submit --platform all --non-interactive