name: EAS Build and Keystore Generation

on:
  push:
    branches:
      - eas

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci

      - name: Decode Android keystore
        env:
          EXPO_ANDROID_KEYSTORE_BASE64: ${{ secrets.EXPO_ANDROID_KEYSTORE_BASE64 }}
        run: |
          echo $EXPO_ANDROID_KEYSTORE_BASE64 | base64 --decode > upload-keystore.jks

      - name: Upload keystore as artifact
        uses: actions/upload-artifact@v2
        with:
          name: android-keystore
          path: upload-keystore.jks