name: Pull Request Checks

on:
  pull_request:
    branches:
      - main

jobs:
  check-and-test:
    name: Check, Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: echo "*** Linting skipped ***" # npm run lint -- --ext .js,.jsx,.ts,.tsx
      - name: Type check
        run: echo "*** Typecheck skipped ***" # npm run typecheck
      - name: Build
        run: npm run build
      - name: Test
        run: npm test