name: Update Badges

on:
  workflow_run:
    workflows: ["EAS Build"]
    types:
      - completed

jobs:
  update-badges:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create badges directory
        run: mkdir -p .github/badges

      - name: Generate Build Badge
        uses: emibcn/badge-action@v1
        with:
          label: 'Build'
          status: ${{ github.event.workflow_run.conclusion }}
          color: ${{ github.event.workflow_run.conclusion == 'success' && 'green' || 'red' }}
          path: '.github/badges/build-badge.svg'

      - name: Generate Test Badge
        uses: emibcn/badge-action@v1
        with:
          label: 'Tests'
          status: ${{ github.event.workflow_run.conclusion }}
          color: ${{ github.event.workflow_run.conclusion == 'success' && 'green' || 'red' }}
          path: '.github/badges/test-badge.svg'

      - name: Commit and Push Badge
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .github/badges/*.svg || true
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update badges" && git push "https://$PAT_TOKEN@github.com/${{ github.repository }}.git" HEAD:${{ github.ref }})

      - name: Check for changes
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          if git diff --quiet && git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git add .github/badges/*.svg
            git commit -m "Update badges"
            git push "https://$PAT_TOKEN@github.com/${{ github.repository }}.git" HEAD:${{ github.ref }}
          fi